# Generated by Django 2.2.19 on 2022-11-05 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(blank=True, choices=[('Gerente', 'Gerente'), ('Atendente', 'Atendente'), ('Faturista', 'Faturista')], max_length=20, verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Compra_fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('tipo', models.CharField(blank=True, choices=[('Mouse', 'Mouse'), ('Teclado', 'Teclado'), ('Headset', 'Headset'), ('Controle', 'Controle'), ('Impressora', 'Impressora'), ('Caixa de Som', 'Caixa de Som')], max_length=20, verbose_name='Tipo')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=30, verbose_name='Modelo')),
                ('xml', models.CharField(max_length=99999, verbose_name='XML')),
            ],
            options={
                'verbose_name': 'Compra Fornecedor',
                'verbose_name_plural': 'Compra Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_logradouro', models.CharField(max_length=200, verbose_name='Logradouro')),
                ('end_numero', models.CharField(blank=True, max_length=10, verbose_name='Numero')),
                ('end_cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('end_bairro', models.CharField(max_length=30, verbose_name='Bairro')),
                ('end_uf', models.CharField(max_length=2, verbose_name='UF')),
                ('end_cidade', models.CharField(max_length=40, verbose_name='Cidade')),
                ('end_complemento', models.CharField(max_length=30, verbose_name='Complemento')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
            ],
            options={
                'verbose_name': 'Estoque',
            },
        ),
        migrations.CreateModel(
            name='Forma_pagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pagamento', models.CharField(blank=True, choices=[('Boleto', 'Boleto'), ('Cartão de crédito', 'Cartão de crédito'), ('Cartão de débito', 'Cartão de débito'), ('pix', 'pix')], max_length=30, verbose_name='Forma de pagamento')),
            ],
            options={
                'verbose_name': 'Forma de pagamento',
                'verbose_name_plural': 'Forma de pagamentos',
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14, verbose_name='CNPJ')),
                ('inscricao_estadual', models.CharField(max_length=9, verbose_name='Inscrição Estadual')),
                ('razao_social', models.CharField(max_length=50, verbose_name='Razão Social')),
                ('contato', models.EmailField(help_text='contato@exemplo.com', max_length=100, verbose_name='Contato')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='Pagamento_nfe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor')),
                ('data', models.DateField(blank=True, help_text='Formato DD/MM/AAAA', null=True, verbose_name='Data de Nascimento')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[('Mouse', 'Mouse'), ('Teclado', 'Teclado'), ('Headset', 'Headset'), ('Controle', 'Controle'), ('Caixa de Som', 'Caixa de Som')], max_length=20, verbose_name='Tipo')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=30, verbose_name='Modelo')),
                ('descricao', models.TextField(max_length=500, verbose_name='Descricao')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, help_text='Formato DD/MM/AAAA', null=True, verbose_name='Data de Nascimento')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('prazo_entrega', models.DateField(blank=True, help_text='Formato DD/MM/AAAA', null=True, verbose_name='Data de Nascimento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.Produto')),
            ],
        ),
        migrations.CreateModel(
            name='Item_pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.Produto')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('data_nascimento', models.DateField(blank=True, help_text='Formato DD/MM/AAAA', null=True, verbose_name='Data de Nascimento')),
                ('email', models.EmailField(max_length=200, verbose_name='email')),
                ('senha', models.CharField(max_length=20, verbose_name='Senha')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Salário')),
                ('cargo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aplic.Cargo')),
                ('endereco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aplic.Endereco')),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('data_nascimento', models.DateField(blank=True, help_text='Formato DD/MM/AAAA', null=True, verbose_name='Data de Nascimento')),
                ('email', models.EmailField(max_length=200, verbose_name='email')),
                ('senha', models.CharField(max_length=20, verbose_name='Senha')),
                ('contato', models.CharField(help_text='DDD + Número de telefone', max_length=11, null=True, verbose_name='Contato:')),
                ('endereco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aplic.Endereco')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(blank=True, to='aplic.Produto')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
