# Generated by Django 2.2.19 on 2022-09-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registo',
            name='senha',
            field=models.TextField(help_text='A senha deve conter letras maiusculas', verbose_name='Senha'),
        ),
    ]
