# Generated by Django 2.2.19 on 2022-10-06 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(blank=True, choices=[('Gerente', 'Gerente'), ('Atendente', 'Atendente'), ('Faturista', 'Faturista')], max_length=100, verbose_name='Cargo')),
            ],
        ),
        migrations.RemoveField(
            model_name='produto',
            name='lote',
        ),
        migrations.AddField(
            model_name='cliente',
            name='contato',
            field=models.CharField(help_text='DDD + Número de telefone', max_length=11, null=True, verbose_name='Contato:'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='senha',
            field=models.CharField(default=0, max_length=20, verbose_name='Senha'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='email',
            field=models.EmailField(default=0, max_length=200, verbose_name='email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='salario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Salário'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='senha',
            field=models.CharField(default=1, max_length=20, verbose_name='Senha'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aplic.Cargo'),
        ),
    ]
