# Generated by Django 2.2.19 on 2022-11-06 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0002_auto_20221105_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='quantidade',
        ),
    ]
