# Generated by Django 2.2.19 on 2022-10-27 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0003_auto_20221006_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='cargo',
            field=models.CharField(blank=True, choices=[('Gerente', 'Gerente'), ('Atendente', 'Atendente'), ('Faturista', 'Faturista')], max_length=20, verbose_name='Cargo'),
        ),
    ]
