# Generated by Django 2.2.19 on 2022-09-26 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0003_auto_20220926_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registo',
            name='senha',
        ),
    ]
