# Generated by Django 2.2.19 on 2022-09-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0004_remove_registo_senha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_produto', models.CharField(max_length=100, verbose_name='Codigo')),
                ('descricao', models.TextField(max_length=500, verbose_name='Descrição')),
                ('lote', models.CharField(max_length=30, verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.DeleteModel(
            name='Registo',
        ),
    ]
