# Generated by Django 2.2.19 on 2022-11-06 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0004_produto_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='foto',
        ),
    ]
