# Generated by Django 2.2.19 on 2022-10-27 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0004_auto_20221026_2105'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estoque',
        ),
        migrations.AlterModelOptions(
            name='cargo',
            options={'verbose_name': 'Cargo', 'verbose_name_plural': 'Cargos'},
        ),
    ]
