# Generated by Django 2.2.19 on 2022-11-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0005_remove_produto_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='image',
            field=models.FileField(default=0, upload_to='produtos/'),
            preserve_default=False,
        ),
    ]
