# Generated by Django 2.2.19 on 2022-09-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0005_auto_20220926_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Preço')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('cod_produto', models.CharField(max_length=20, verbose_name='Código')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
            },
        ),
    ]
