# Generated by Django 2.2.19 on 2022-09-26 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0006_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_logradouro', models.CharField(max_length=200, verbose_name='Logradouro')),
                ('end_numero', models.CharField(blank=True, max_length=10, verbose_name='Número')),
                ('end_cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('end_bairro', models.CharField(max_length=30, verbose_name='Bairro')),
                ('end_uf', models.CharField(max_length=2, verbose_name='UF')),
                ('end_cidade', models.CharField(max_length=40, verbose_name='Cidade')),
                ('end_complemento', models.CharField(max_length=30, verbose_name='Complemento')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
        migrations.AlterField(
            model_name='produto',
            name='cod_produto',
            field=models.CharField(max_length=100, verbose_name='Código'),
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('endereco_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aplic.Endereco')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.TextField(max_length=11, verbose_name='CPF')),
                ('data_nascimento', models.DateField(blank=True, help_text='Formato DD/MM/AAAA', null=True, verbose_name='Data de Nascimento')),
                ('id_funcionario', models.CharField(max_length=5, verbose_name='ID')),
                ('cargo', models.CharField(blank=True, choices=[('Gerente', 'Gerente'), ('Atendente', 'Atendente')], max_length=100, verbose_name='Cargo')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='aplic.Endereco')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'abstract': False,
            },
            bases=('aplic.endereco', models.Model),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('endereco_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aplic.Endereco')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.TextField(max_length=11, verbose_name='CPF')),
                ('data_nascimento', models.DateField(blank=True, help_text='Formato DD/MM/AAAA', null=True, verbose_name='Data de Nascimento')),
                ('id_cliente', models.CharField(max_length=5, verbose_name='ID')),
                ('email', models.EmailField(max_length=200, verbose_name='email')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='aplic.Endereco')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
            bases=('aplic.endereco', models.Model),
        ),
    ]
