# Generated by Django 2.2.19 on 2022-10-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0006_estoque_forma_pagamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estoque',
            options={'verbose_name': 'Estoque'},
        ),
        migrations.RemoveField(
            model_name='forma_pagamento',
            name='Forma_pagamento',
        ),
        migrations.AddField(
            model_name='forma_pagamento',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('Boleto', 'Boleto'), ('Cartão de crédito', 'Cartão de crédito'), ('Cartão de débito', 'Cartão de débito'), ('pix', 'pix')], max_length=30, verbose_name='Forma de pagamento'),
        ),
    ]
