# Generated by Django 2.2.19 on 2022-10-27 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0007_auto_20221027_1251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forma_pagamento',
            options={'verbose_name': 'Forma de pagamento', 'verbose_name_plural': 'Forma de pagamentos'},
        ),
    ]
