# Generated by Django 2.2.19 on 2022-11-06 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0007_auto_20221106_0457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='image',
        ),
    ]
