# Generated by Django 2.2.19 on 2022-11-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0008_remove_produto_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='produtos/'),
        ),
    ]
