# Generated by Django 2.2.19 on 2022-11-07 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0012_auto_20221106_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
