# Generated by Django 2.2.19 on 2022-11-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0013_auto_20221106_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='slug',
            field=models.SlugField(default='slug_padrao'),
            preserve_default=False,
        ),
    ]
