# Generated by Django 2.2.19 on 2022-11-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0014_produto_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
