# Generated by Django 2.2.19 on 2022-11-07 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0019_auto_20221107_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='slug',
            field=models.SlugField(default='slug_padrao'),
        ),
    ]
