# Generated by Django 2.2.19 on 2022-11-08 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0022_auto_20221108_0306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[('Mouse', 'Mouse'), ('Teclado', 'Teclado'), ('Headset', 'Headset'), ('Controle', 'Controle'), ('Caixa de Som', 'Caixa de Som')], max_length=20, verbose_name='Tipo')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=30, verbose_name='Modelo')),
                ('descricao', models.TextField(max_length=500, verbose_name='Descricao')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('featured', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.RemoveField(
            model_name='item_pedido',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='produto',
        ),
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, to='aplic.Product'),
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.AddField(
            model_name='item_pedido',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='aplic.Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='aplic.Product'),
            preserve_default=False,
        ),
    ]
