# Generated by Django 2.2.19 on 2022-11-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0023_auto_20221108_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, max_length=250, verbose_name='title'),
        ),
    ]
