# Generated by Django 2.2.19 on 2022-11-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0024_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(default='Product', max_length=250, verbose_name='title'),
        ),
    ]
