# Generated by Django 2.2.19 on 2022-11-09 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0025_auto_20221108_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='descricao',
            field=models.TextField(max_length=10000, verbose_name='Descricao'),
        ),
    ]
