# Generated by Django 2.2.19 on 2022-11-11 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0026_auto_20221108_2258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(default='Product', max_length=250, verbose_name='Título'),
        ),
    ]
