# Generated by Django 2.2.19 on 2022-11-12 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0027_auto_20221111_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Mouse', 'Mouse'), ('Teclado', 'Teclado'), ('Headset', 'Headset'), ('Controle', 'Controle'), ('Caixa de Som', 'Caixa de Som'), ('Monitor', 'Monitor')], max_length=20, verbose_name='Tipo'),
        ),
    ]
