# Generated by Django 2.2.19 on 2022-11-12 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0027_auto_20221111_1903'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
