# Generated by Django 2.2.19 on 2022-11-12 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0028_delete_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.CharField(default='user', max_length=100, verbose_name='nome de usuario'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='user',
            field=models.CharField(default='user', max_length=100, verbose_name='nome de usuario'),
        ),
    ]
