# Generated by Django 2.2.19 on 2022-11-12 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0028_auto_20221111_2145'),
        ('aplic', '0029_auto_20221112_0149'),
    ]

    operations = [
    ]
