# Generated by Django 2.2.19 on 2022-11-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0031_auto_20221112_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(default=0, max_length=11, verbose_name='CPF'),
            preserve_default=False,
        ),
    ]
