# Generated by Django 2.2.19 on 2022-11-12 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0032_funcionario_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='endereco',
        ),
        migrations.AlterModelOptions(
            name='endereco',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.DeleteModel(
            name='Funcionario',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
