# Generated by Django 2.2.19 on 2022-11-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0034_auto_20221112_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='contato',
            field=models.CharField(blank=True, help_text='DDD + Número', max_length=11, null=True, verbose_name='Telefone Celular'),
        ),
    ]
