# Generated by Django 2.2.19 on 2022-11-12 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0035_usuario_contato'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
    ]
