# Generated by Django 2.2.19 on 2022-11-12 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0036_auto_20221112_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='endereco',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='aplic.Endereco'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=200, verbose_name='E-mail'),
        ),
    ]
