# Generated by Django 2.2.19 on 2022-11-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0037_auto_20221112_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='salario',
            field=models.IntegerField(default=0, verbose_name='Salário'),
            preserve_default=False,
        ),
    ]
