# Generated by Django 2.2.19 on 2022-11-12 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0039_funcionario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='senha',
        ),
    ]
