# Generated by Django 4.1.3 on 2022-11-25 00:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 24, 21, 2, 8, 711424)),
        ),
    ]
