# Generated by Django 4.1.3 on 2022-11-25 14:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_technicalinformation'),
        ('dashboard', '0002_alter_vendas_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendas',
            name='nome_produto',
        ),
        migrations.AddField(
            model_name='vendas',
            name='produto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='products.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendas',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 25, 11, 32, 24, 556482)),
        ),
    ]
