# Generated by Django 4.1.3 on 2022-11-25 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_vendas_nome_produto_vendas_produto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 25, 11, 36, 11, 780903)),
        ),
    ]
