# Generated by Django 4.1.3 on 2022-11-18 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='titulacao',
            field=models.CharField(blank=True, choices=[('Mouse', 'Mouse'), ('Teclado', 'Teclado'), ('Controle', 'Controle'), ('Headset', 'Headset'), ('Monitor', 'Monitor'), ('Caixa de som', 'Caixa de som')], max_length=100, verbose_name='Titulação'),
        ),
    ]
