# Generated by Django 4.1.3 on 2022-11-19 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_titulacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='titulacao',
        ),
        migrations.AddField(
            model_name='product',
            name='productType',
            field=models.CharField(blank=True, choices=[('Mouse', 'Mouse'), ('Teclado', 'Teclado'), ('Controle', 'Controle'), ('Headset', 'Headset'), ('Monitor', 'Monitor'), ('Caixa de som', 'Caixa de som')], max_length=100, verbose_name='Tipo de produto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Destaque'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='products/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=20, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Título'),
        ),
    ]
