# Generated by Django 4.1.3 on 2022-11-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_product_titulacao_product_producttype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='technicalInformation',
            field=models.TextField(blank=True, verbose_name='Informações técnicas'),
        ),
    ]
